name: deploy

on:
  workflow_dispatch

env:
  SERVER_HOST: # ip адрес сервера
  SERVER_USER: root
  SERVER_PATH: /root/project

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.3.1
        with:
          key: "${{ secrets.MY_KEY }}"
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"

      - name: Generate known_hosts
        run: ssh-keyscan -H ${{ env.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Sync project files to server
        run: rsync --archive --compress --delete --progress ./ ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }}:${{ env.SERVER_PATH }} --exclude=".env"

      - name: Run docker-compose on server
        run: |
          ssh ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }} << EOF
            cd ${{ env.SERVER_PATH }}
            docker compose down || true
            docker compose up --build -d
          EOF
